### ISSUE TITLE
Question about the license of the project

### ISSUE THREAD

**Issue by Soulou** [1024pix/gravitee-buildpack#4]
Hello the Pix Team

We'd like to use and contribute to this buildpack, but to do so, we'd like to know which license is used by this repository.

Can you please add a `LICENSE` file in it?

Thanks!

**Comment by yahyayouness** [comment]
Thank you for your feedback, the "GNU AFFERO GENERAL PUBLIC LICENSE" has been added to the project.

**Comment by Soulou** [comment]
Thanks all good to me
